sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 7
    Sector0:
      start: 0
      end: 44
      scaling: 0.2
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 45
      end: 90
      scaling: 0.4
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 91
      end: 141
      scaling: 0.2
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 142
      end: 206
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 207
      end: 249
      scaling: 0.2
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 250
      end: 381
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 382
      end: 382
      scaling: 0.3
      only_FTG: false
      no_FTG: false
